server:
  port: 2001

spring:
  application:
    name: seata-orders-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root

  cloud:
    alibaba:
      seata:
        enableAutoDataSourceProxy: false
        tx-service-group: seata_test_tx_group  # 事务组名称
        registry:
          file:
            #因为seata版本驼峰参数映射有问题导致，seata的zk配置参数设置不上导致异常
            name: registry.conf
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
feign:
  hystrix:
    enabled: true  # 开启feign的支持

logging:
  level:
    io:
      seata: info

ribbon:
  ReadTimeout: 6000 #//处理请求的超时时间，默认为1秒   GlobalTransactional 默认超时也是6000
  ConnectTimeout: 6000 #连接建立的超时时长，默认1秒    GlobalTransactional 默认超时也是6000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.i520java.seata.entity




